---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
        exclude: LICENSE
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries, "119", --wrap-descriptions, "119"]
  - repo: local
    hooks:
      - id: py-format
        name: Formatting python
        entry: make format
        language: system
        require_serial: true
        files: \.py$
      - id: py-lint
        name: Linting python
        entry: make lint
        language: system
        files: \.pyi?$
